version: '3.9'

services:
  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge:latest
    restart: unless-stopped
    environment:
      ACCEPT_EULA: '1'
      MSSQL_SA_PASSWORD: 'YourStrong(!)Password'
    ports:
      - '1433:1433'
    volumes:
      - mssql-data:/var/opt/mssql
  backend:
    build:
      context: ./server
      target: dependencies
    command: npm run dev
    ports:
      - '3000:3000'
    env_file:
      - server/.env
    environment:
      DATABASE_URL: sqlserver://sa:YourStrong(!)Password@sqlserver:1433;database=airplanecheck
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - sqlserver

volumes:
  mssql-data:
