version: '3.9'

services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: airplanecheck
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
  backend:
    build:
      context: ./server
      target: dependencies
    command: npm run dev
    ports:
      - '3000:3000'
    env_file:
      - server/.env
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/airplanecheck
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db

volumes:
  postgres-data:
